name: Unittest

on:
  push:
    branches: [hw_asr_2022]
  pull_request:
    branches: [hw_asr_2022]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      python-version: "3.9.13"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install -y libsndfile1 libsndfile1-dev
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run hw_asr/tests
        run: |
          python -m unittest discover hw_asr/tests